In [37]:
import numpy as np

In [ ]:
H = [[9, 2, 3, 4, 0, 0, 7, 8, 0],
	 [1, 0, 0, 2, 3, 0, 5, 0, 0],
	 [0, 0, 0, 1, 0, 0, 2, 3, 0],
	 [4, 3, 0, 0, 0, 2, 0, 0, 1],
	 [0, 0, 1, 0, 0, 0, 0, 2, 3],
	 [8, 7, 0, 6, 0, 5, 0, 0, 4],
     [0, 1, 0, 0, 2, 3, 4, 0, 0], 
	 [0, 9, 0, 8, 0, 7, 0, 6, 5],
	 [0, 0, 0, 0, 1, 9, 0, 0, 8]]

X_0 = np.zeros((9, 9), dtype=np.int8)
X = X_0 + H

In [43]:
def scan_row(row: int, target: int) -> bool:
	row_nums = X.tolist()[row]
	if target in row_nums:
		return False
	else:
		return True
	
def scan_col(col: int, target: int) -> bool:
	col_nums = [X[i][col] for i in range(9)]
	if target in col_nums:
		return False
	else:
		return True

def get_box(row: int, col: int) -> np.ndarray:
	row_range: tuple = (row//3*3, row//3*3+3)
	col_range: tuple = (col//3*3, col//3*3+3)
	return X[row_range[0]:row_range[1], col_range[0]:col_range[1]]

def scan_box(row: int, col: int, target: int) -> bool:
	box_nums = get_box(row, col)
	if target in box_nums:
		return False
	else:
		return True

def is_valid(row: int, col: int, target: int) -> bool:
	return scan_row(row, target) and scan_col(col, target) and scan_box(row, col, target)

# 確定しているものと、確定していないものを分ける
# 確定しているものは、そのままにしておく
# 順番に、確定していないマスに対して、1から9までの数字を入れていく

for row in range(9):
	for col in range(9):
		if X[row, col] == 0:
			for target in range(1, 10):
				if is_valid(row, col, target):
					X[row, col] = target
					print(X)
					break
				# ここまできたら、そのマスには数字が入らない状況だから，どこか間違っているはず．
				X[row, col] = 0
		else:
			pass

if X.sum() == 405:
	print("Solved!")
	print(X)

else:
	print("Failed!")
	pass

[[5 2 3 4 0 0 7 8 0]
 [1 0 0 2 3 0 5 0 0]
 [0 0 0 1 0 0 2 3 0]
 [4 3 0 0 0 2 0 0 1]
 [0 0 1 0 0 0 0 2 3]
 [8 7 0 6 0 5 0 0 4]
 [0 1 0 0 2 3 4 0 0]
 [0 9 0 8 0 7 0 6 5]
 [0 0 0 0 1 9 0 0 8]]
[[5 2 3 4 6 0 7 8 0]
 [1 0 0 2 3 0 5 0 0]
 [0 0 0 1 0 0 2 3 0]
 [4 3 0 0 0 2 0 0 1]
 [0 0 1 0 0 0 0 2 3]
 [8 7 0 6 0 5 0 0 4]
 [0 1 0 0 2 3 4 0 0]
 [0 9 0 8 0 7 0 6 5]
 [0 0 0 0 1 9 0 0 8]]
[[5 2 3 4 6 0 7 8 9]
 [1 0 0 2 3 0 5 0 0]
 [0 0 0 1 0 0 2 3 0]
 [4 3 0 0 0 2 0 0 1]
 [0 0 1 0 0 0 0 2 3]
 [8 7 0 6 0 5 0 0 4]
 [0 1 0 0 2 3 4 0 0]
 [0 9 0 8 0 7 0 6 5]
 [0 0 0 0 1 9 0 0 8]]
[[5 2 3 4 6 0 7 8 9]
 [1 4 0 2 3 0 5 0 0]
 [0 0 0 1 0 0 2 3 0]
 [4 3 0 0 0 2 0 0 1]
 [0 0 1 0 0 0 0 2 3]
 [8 7 0 6 0 5 0 0 4]
 [0 1 0 0 2 3 4 0 0]
 [0 9 0 8 0 7 0 6 5]
 [0 0 0 0 1 9 0 0 8]]
[[5 2 3 4 6 0 7 8 9]
 [1 4 6 2 3 0 5 0 0]
 [0 0 0 1 0 0 2 3 0]
 [4 3 0 0 0 2 0 0 1]
 [0 0 1 0 0 0 0 2 3]
 [8 7 0 6 0 5 0 0 4]
 [0 1 0 0 2 3 4 0 0]
 [0 9 0 8 0 7 0 6 5]
 [0 0 0 0 1 9 0 0 8]]
[[5 2 3 4 6 0 7 8 9]
 [1 4 6 2 3 8 5 0 0]
 [0 0 0 

In [36]:
X.sum()

321

In [5]:
i = 0
j = 0

if X[i, j] == 0:
	while i < 9:
		while j < 9:
			if X[i, j] == 0:
				for n in range(1, 10):
					if n not in X[i, :] and n not in X[:, j]:
						X[i, j] = n
						j += 1
						break
					else:
						continue
			else:
				j += 1
		i += 1

In [6]:
X

array([[5, 2, 3, 4, 6, 1, 7, 8, 9],
       [1, 0, 0, 2, 3, 0, 5, 0, 0],
       [0, 0, 0, 1, 0, 0, 2, 3, 0],
       [4, 3, 0, 0, 0, 2, 0, 0, 1],
       [0, 0, 1, 0, 0, 0, 0, 2, 3],
       [8, 7, 0, 6, 0, 5, 0, 0, 4],
       [0, 1, 0, 0, 2, 3, 4, 0, 0],
       [0, 9, 0, 8, 0, 7, 0, 6, 5],
       [0, 0, 0, 0, 1, 9, 0, 0, 8]])